In [1]:
import torch
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import torch.nn as nn
print(torch.__version__)

2.13.0+cpu

In [2]:
class Model(nn.Module):

    def __init__(self, num_feature):

        super().__init__()

        self.linear = nn.Linear(num_feature, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()


    def forward(self, features):
        out = self.linear(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)

        return out

In [3]:
features = torch.rand(10,5)

model = Model(features.shape[1])

model(features)

tensor([[0.4697],
        [0.4734],
        [0.5162],
        [0.4602],
        [0.5022],
        [0.4917],
        [0.5118],
        [0.4870],
        [0.4771],
        [0.4979]], grad_fn=<SigmoidBackward0>)

In [4]:
model.linear.bias

Parameter containing:
tensor([0.0393, 0.3163, 0.1228], requires_grad=True)

In [5]:
vector = torch.tensor([7,7])

In [11]:
vector.ndim

1

In [9]:
MATRIX = torch.tensor([[7,8], [9,10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
TENSOR = torch.tensor([[
    [1,2,3],
    [4,9,6],
    [2,8,9]
]])

TENSOR

tensor([[[1, 2, 3],
         [4, 9, 6],
         [2, 8, 9]]])

In [3]:
random_tensor = torch.rand(2,3)

random_tensor

tensor([[0.9538, 0.1124, 0.4544],
        [0.4197, 0.3478, 0.6012]])

In [4]:
random_tensor.T

tensor([[0.9538, 0.4197],
        [0.1124, 0.3478],
        [0.4544, 0.6012]])

In [10]:
mat1 = torch.tensor([
    [2,4,6], 
    [7,3,6]])

mat2 = torch.tensor([
    [3,9], 
    [2,4],
    [4,6]])

matC = mat1 @ mat2

In [18]:
x = torch.arange(1., 10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [21]:
x.shape

torch.Size([9])

In [27]:
x_reshape = x.reshape(1,9)
x_reshape

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [32]:
x_reshape.squeeze().shape

torch.Size([9])

In [30]:
x_reshape.shape

torch.Size([1, 9])

In [25]:
random_image_size_tensor = torch.rand(3, 224, 224, 3)

random_image_size_tensor.shape

torch.Size([3, 224, 224, 3])

In [2]:
data = pd.read_csv("../data/breast-cancer.csv")

In [3]:
data.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [4]:
data.value_counts(["diagnosis"])

diagnosis
B            357
M            212
Name: count, dtype: int64

In [5]:
data.shape

(569, 32)

In [6]:
X = data.iloc[:, 2:]
y = data.iloc[:, 1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [7]:
X

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [8]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
X_train

array([[-0.97102023, -1.00539957, -0.98637646, ..., -1.21522549,
        -0.97016396, -0.8711402 ],
       [ 1.47201912,  0.92601125,  1.50224866, ...,  0.60842674,
         0.02117983, -0.42098688],
       [ 1.41835698, -0.19026722,  1.35499274, ...,  1.39444517,
         1.00772678, -0.05873332],
       ...,
       [-0.62080418,  1.24074291, -0.6039201 , ...,  0.06850517,
        -0.49208042, -0.08164053],
       [-0.78179059,  0.21956321, -0.60514723, ...,  2.11632926,
         5.96604464,  4.73899548],
       [ 0.58518171,  0.55920169,  0.61871312, ..., -0.16267672,
        -0.27302543, -0.24039282]], shape=(455, 30))

In [10]:
y_train

144    B
244    M
56     M
330    M
324    B
      ..
151    B
113    B
445    B
3      M
329    M
Name: diagnosis, Length: 455, dtype: str

In [11]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [12]:
y_train

array([0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1])

In [13]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [14]:
X_train_tensor.shape

torch.Size([455, 30])

In [15]:
X_train_tensor

tensor([[-0.9710, -1.0054, -0.9864,  ..., -1.2152, -0.9702, -0.8711],
        [ 1.4720,  0.9260,  1.5022,  ...,  0.6084,  0.0212, -0.4210],
        [ 1.4184, -0.1903,  1.3550,  ...,  1.3944,  1.0077, -0.0587],
        ...,
        [-0.6208,  1.2407, -0.6039,  ...,  0.0685, -0.4921, -0.0816],
        [-0.7818,  0.2196, -0.6051,  ...,  2.1163,  5.9660,  4.7390],
        [ 0.5852,  0.5592,  0.6187,  ..., -0.1627, -0.2730, -0.2404]],
       dtype=torch.float64)

In [16]:
class MySimpleNN():

    def __init__(self, X):
        self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

    def forward(self, X):
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss_function(self, y_pred, y):
        # clamp prediction to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss

In [17]:
learning_rate = 0.1
epochs = 25

In [18]:
# Create model
model = MySimpleNN(X_train_tensor)

# Define loop
for epoch in range(epochs):

    # Forward pass
    y_pred = model.forward(X_train_tensor)

    # Loss calculate
    loss = model.loss_function(y_pred, y_train_tensor)

    # Backward pass
    loss.backward()

    # parameters update
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # Zero gradiens
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # print loss in each epoch
    print(f"Epoch: {epoch + 1}, Loss: {loss.item()}")

Epoch: 1, Loss: 3.4377224731740634
Epoch: 2, Loss: 3.302132439205851
Epoch: 3, Loss: 3.160456020500589
Epoch: 4, Loss: 3.0137499963047154
Epoch: 5, Loss: 2.857587500169941
Epoch: 6, Loss: 2.6981504483191427
Epoch: 7, Loss: 2.5325316142541587
Epoch: 8, Loss: 2.359207907717281
Epoch: 9, Loss: 2.189054791115478
Epoch: 10, Loss: 2.0177608474301603
Epoch: 11, Loss: 1.8441403532449352
Epoch: 12, Loss: 1.6721694570778918
Epoch: 13, Loss: 1.511596221175977
Epoch: 14, Loss: 1.3646955699154488
Epoch: 15, Loss: 1.233810582425928
Epoch: 16, Loss: 1.1210086305272042
Epoch: 17, Loss: 1.0276333357965395
Epoch: 18, Loss: 0.9538112028962289
Epoch: 19, Loss: 0.8980605794651557
Epoch: 20, Loss: 0.8573784329086057
Epoch: 21, Loss: 0.8280276671649803
Epoch: 22, Loss: 0.8065633252459762
Epoch: 23, Loss: 0.7903807661436679
Epoch: 24, Loss: 0.7777156120443544
Epoch: 25, Loss: 0.7674328337210571

In [19]:
model.bias

tensor([-0.1411], dtype=torch.float64, requires_grad=True)

In [20]:
# Model Evaluation
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.567251443862915